# Generated by Django 2.1.4 on 2018-12-08 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0002_auto_20181208_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mon', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beg', models.TimeField(default=datetime.time(8, 0))),
                ('end', models.TimeField(default=datetime.time(20, 0))),
            ],
        ),
        migrations.CreateModel(
            name='WeekView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(to='course_sched.Day')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='has_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_needs_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='needs_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.CharField(default='Faculty', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(default='Serra', max_length=50),
        ),
        migrations.AddField(
            model_name='day',
            name='time_slots',
            field=models.ManyToManyField(to='course_sched.TimeSlot'),
        ),
    ]
