# Generated by Django 2.1.4 on 2018-12-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0003_auto_20181208_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserved_time',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='course_sched.WeekView'),
        ),
    ]
