# Generated by Django 2.1.4 on 2018-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0004_room_reserved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='@sandiego.edu', max_length=254),
        ),
    ]
