# Generated by Django 2.1.4 on 2018-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0005_faculty_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='course_preference',
            field=models.ManyToManyField(to='course_sched.Course'),
        ),
    ]
