# Generated by Django 2.1.4 on 2018-12-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0006_faculty_course_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='day_preference',
            field=models.ManyToManyField(to='course_sched.Day'),
        ),
    ]
