# Generated by Django 2.1.4 on 2018-12-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0007_faculty_day_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.IntegerField(default=1),
        ),
    ]
