# Generated by Django 2.1.4 on 2018-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0008_course_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2019)),
            ],
        ),
    ]
