# Generated by Django 2.1.4 on 2018-12-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_sched', '0009_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='cannot_conflict',
            field=models.ManyToManyField(related_name='_course_cannot_conflict_+', to='course_sched.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='suggested_faculty',
            field=models.ManyToManyField(to='course_sched.Faculty'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='course_sched.Course'),
        ),
    ]
